# Generated by Django 5.2 on 2025-04-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PGS_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='roletype',
            field=models.CharField(choices=[('technical', 'Technical'), ('business', 'Business')], default='technical', max_length=100),
        ),
    ]
