# Generated by Django 5.2 on 2025-04-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PGS_App', '0002_roles_roletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalgoldsource',
            name='ext_leaveend_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalgoldsource',
            name='ext_leavestart_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalgoldsource',
            name='lwd_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalgoldsource',
            name='resignation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalgoldsource',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roles',
            name='roletype',
            field=models.CharField(choices=[('technical', 'Technical'), ('business', 'Business'), ('tbd', 'TBD')], default='tbd', max_length=100),
        ),
    ]
