# Generated by Django 5.2 on 2025-04-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PGS_App', '0003_alter_personalgoldsource_ext_leaveend_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalgoldsource',
            name='employeeid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalgoldsource',
            name='employeetype',
            field=models.CharField(blank=True, choices=[('regular', 'Regular'), ('contractor', 'Contractor')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personalgoldsource',
            name='jobtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personalgoldsource',
            name='location',
            field=models.CharField(blank=True, choices=[('bangalore', 'Bangalore'), ('canada', 'Canada'), ('chennai', 'Chennai'), ('puerto rico', 'Puerto Rico'), ('usa', 'USA')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personalgoldsource',
            name='peoplemanager',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
