# Generated by Django 5.2 on 2025-04-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PGS_App', '0004_alter_personalgoldsource_employeeid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalgoldsource',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='personalgoldsource',
            name='employeeid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
