# Generated by Django 5.2 on 2025-04-11 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PGS_App", "0005_alter_personalgoldsource_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobLevel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Role_Skill",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="personalgoldsource",
            name="todaysdate",
        ),
        migrations.AddField(
            model_name="personalgoldsource",
            name="orgunit2_desc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personalgoldsource",
            name="orgunit3_desc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personalgoldsource",
            name="orgunit4_desc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personalgoldsource",
            name="orgunit5_desc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personalgoldsource",
            name="orgunit6_desc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personalgoldsource",
            name="projectmoon",
            field=models.CharField(
                choices=[("yes", "YES"), ("no", "NO")], default="no", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="personalgoldsource",
            name="region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("canada", "Canada"),
                    ("mexico", "Mexico"),
                    ("us1", "US1"),
                    ("us2", "US2"),
                    ("us4", "US4"),
                    ("us5", "US5"),
                    ("india", "India"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="personalgoldsource",
            name="shorecalc",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="personalgoldsource",
            name="supplier_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="personalgoldsource",
            name="timeofservice",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="personalgoldsource",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("resigned", "Resigned"),
                    ("extended leave", "Extended Leave"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="roles",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="personalgoldsource",
            name="joblevel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="PGS_App.joblevel",
            ),
        ),
        migrations.AddField(
            model_name="personalgoldsource",
            name="roleskill1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roleskill1",
                to="PGS_App.role_skill",
            ),
        ),
        migrations.AddField(
            model_name="personalgoldsource",
            name="roleskill2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roleskill2",
                to="PGS_App.role_skill",
            ),
        ),
        migrations.AddField(
            model_name="personalgoldsource",
            name="roleskill3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roleskill3",
                to="PGS_App.role_skill",
            ),
        ),
        migrations.AddField(
            model_name="personalgoldsource",
            name="roleskill4",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roleskill4",
                to="PGS_App.role_skill",
            ),
        ),
        migrations.AddField(
            model_name="personalgoldsource",
            name="roleskill5",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roleskill5",
                to="PGS_App.role_skill",
            ),
        ),
    ]
