from PGS_App.models import Role_Skill


# List of Role Skill Titles
role_skill_titles = [
    ".Net",
    "Active Directory",
    "AI/ML/Data Science",
    "Angular",
    "Apache Nifi",
    "API Security",
    "API Testing",
    "Appian",
    "Automation",
    "AWS",
    "Azure",
    "Azure DevOps",
    "Back End Engineering",
    "BDD Framework",
    "Big Data",
    "Bootstrap",
    "BRMS - Inrule",
    "C#",
    "C++",
    "CI/CD",
    "Claims Engine 2000 (Daytech)",
    "Cloudera",
    "Cobol/CICS",
    "Configuration",
    "Containerization",
    "CSS",
    "Data Analysis",
    "Data Engineering",
    "Data Modelling",
    "Data Visualization",
    "Data Warehouse",
    "Databricks",
    "DataDog",
    "DBA",
    "Delivery Management",
    "Drools",
    "Dy260/280",
    "EDI",
    "Elastic Search",
    "ETL",
    "Full Stack",
    "Functional Testing",
    "GCP",
    "Git",
    "Great Expectations",
    "H2 database",
    "Hadoop",
    "HIVE",
    "HTML",
    "IIR - Fuzzy Matching",
    "Informatica",
    "Informatica - BDM",
    "Informatica - Data Transformation",
    "Informatica - Power Center",
    "Informatica - Power Exchange",
    "Inrule",
    "Integration Testing",
    "Java",
    "Java SOAP based WebServices",
    "JavaScript",
    "Jmeter",
    "JPA, Hibernate",
    "Jquery",
    "Junit",
    "K2",
    "Kotlin",
    "Mainframe",
    "Messaging - JMS, RabbitMQ, ASB, Kafka",
    "MF/DB2",
    "Micro services",
    "Micro Strategy",
    "MLFlow",
    "Mobile Application Development",
    "Mongo DB",
    "MVC",
    "NVDA",
    "OAuth 2.0",
    "Oracle",
    "Outsystems",
    "Pearl",
    "Performance Testing",
    "PL/SQL",
    "Postgresql",
    "Power BI",
    "Power Shell",
    "Prescriptive Analytics",
    "Process Modeling",
    "Project Management",
    "Python",
    "QA Automation",
    "QNX",
    "ReactJS",
    "ReadyAPI, SOAP UI, Postman",
    "Regression Testing",
    "Reinforcement Learning",
    "RPA",
    "Safe Agile",
    "SAS",
    "Selenium",
    "Site Reliability",
    "Sitecore",
    "Software developer engineer in test (SDET)",
    "SonarQube",
    "SPARK/PYSPARK",
    "Spring Batch",
    "Spring Boot, Spring Framework",
    "SQL",
    "SQL Server",
    "SSIS",
    "SSRS",
    "Swagger 2.0",
    "Tableau",
    "TERADATA",
    "Test Driven Development",
    "UI UX",
    "Unified Functional Test (UFT) Scripting",
    "UNIX SCRIPT",
    "Veracode",
    "Vertica",
    "Vmware Tanzu",
    "WayDev"
]

# Create Role_Skill objects
role_skills = [Role_Skill(title=title) for title in role_skill_titles]

# Bulk insert into the database
Role_Skill.objects.bulk_create(role_skills, ignore_conflicts=True)

print(f"{len(role_skills)} Role Skills imported successfully!")